export default {
    GET_ALL:'GET_ALL',
    FILTER:'FILTER',
    GENERIC:'GENERIC',
    COMMERCIAL:'COMMERCIAL',
    CLEAR:'CLEAR',
    REFRESH:'REFRESH',
    ADD:'ADD',
    REMOVE:'REMOVE',
    CHANGE:'CHANGE',
    ADD_VALUE:'ADD_VALUE',
    REMOVE_VALUE:'REMOVE_VALUE',
    UPDATE:'UPDATE'
}